default: &default
  adapter: mysql2
  encoding: utf8mb4
  username: <%= ENV['DB_USER_NAME'] %>
  password: <%= ENV['DB_PASSWORD'] %>
  host: <%= ENV['DB_HOST'] %>
  port: <%= ENV['DB_PORT'] %>

development:
  <<: *default
  database: building_locations_db

test:
  <<: *default
  database: building_locations_db_test

production:
  <<: *default
  database: careers_db